title: 0xmanyu
description: Offensive Security Portfolio | Penetration Testing | Write-ups
theme: jekyll-theme-midnight
author: Manyu Simha Ravi
email: manyusimha26@gmail.com
github_username: manyu2024
url: "https://manyu2024.github.io"